In [1]:
import numpy as np

In [2]:
"""
##
Algorithm insert sort (low to high values)
##
"""

A = np.array([5,2,12,4,8, 6,1,3])

for j in range(1, len(A)):
    key = A[j]   # value, which we will be replace 
    i = j - 1 # iter for compare vith previos values and shifting
    while (i >= 0 and A[i] > key): # if previos value less key
        A[i+1] = A[i] # next (key position) = previos value
        i = i - 1 # and increment iter        
    A[i+1] = key # in the end this cicle operation initialise next value as key
    
A  

array([ 1,  2,  3,  4,  5,  6,  8, 12])

In [3]:
def insertSortApp1(A):
    """
    ##
        Algorithm insert sort (high to low)
        Approach 1
    ##
    A - input 1D array
    """
    for j in np.arange(len(A)-2, -1, -1 ):
        key = A[j]   
        i = j + 1 
        while (A[i] > key and i <= len(A)-1): 
            A[i-1] = A[i] 
            i = i + 1      
            if i >=len(A)-1:
                break;
        A[i-1] = key # in the end this cicle operation initialise next value as key
    return A

def insertSortApp2(A):
    """
    ##
        Algorithm insert sort (high to low)
        Approach 2
    ##
    A - input 1D array
    """
    for j in range(1, len(A)):
        key = A[j]   # value, which we will be replace 
        i = j - 1 # iter for compare vith previos values and shifting
        while (i >= 0 and A[i] < key): # if previos value more key
            A[i+1] = A[i] # next (key position) = previos value
            i = i - 1 # and decrement iter        
        A[i+1] = key # in the end this cicle operation initialise next value as key
    return A


A = np.array([5,2,12,4,8, 6,1,3])

print (insertSortApp1(A))
print (insertSortApp2(A))

[12  8  6  5  4  3  2  1]
[12  8  6  5  4  3  2  1]


In [4]:
"""
##
MergeSort algorithm
##
"""

def mergesort(x):
        
    if len(x) == 1: # condition for exit
        return x
    
    middle = (len(x) // 2)  # devide array on two part
    
    L = mergesort(x[:middle]) # recursive procedure`s for call mergesort
    R = mergesort(x[middle:])

    result = []

    i = j = 0; # initialise index for 

    while i < len(L) and j < len(R):
        if L[i] < R[j]:
            result.append(L[i])
            i += 1
        else:
            result.append(R[j])
            j += 1
    
    result += L[i:]
    result += R[j:]

    return result

A = [5,2,12,4]

mergesort(A)

[2, 4, 5, 12]

In [5]:
from math import floor

"""
##
binarySearch algorithm
##
"""

def binarySearch(A, begin, end, valueSearch):
    
    middle = int(floor((begin+end)/2)) # compute middle value of array
    
    if A[middle] == valueSearch:
        return middle
    
    elif begin==end:
        return None
    
    elif A[middle] > valueSearch:
        return binarySearch(A, begin, middle-1, valueSearch)
    
    else:
        return binarySearch(A, middle+1, end, valueSearch)

a = [1, 2, 3, 4, 5, 7,77]

print ('index result: %d' % binarySearch(a, 0, len(a), 3))

index result: 2
